//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOB.UI.Core.View.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LOB.UI.Core.View.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Menu_File.
        /// </summary>
        public static string Menu_File {
            get {
                return ResourceManager.GetString("Menu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Menu_Quit.
        /// </summary>
        public static string Menu_File_Quit {
            get {
                return ResourceManager.GetString("Menu_File_Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Menu_Save.
        /// </summary>
        public static string Menu_File_Save {
            get {
                return ResourceManager.GetString("Menu_File_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Menu_List.
        /// </summary>
        public static string Menu_List {
            get {
                return ResourceManager.GetString("Menu_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Menu_List_Client.
        /// </summary>
        public static string Menu_List_Client {
            get {
                return ResourceManager.GetString("Menu_List_Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Menu_List_Company.
        /// </summary>
        public static string Menu_List_Company {
            get {
                return ResourceManager.GetString("Menu_List_Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Menu_List_Employee.
        /// </summary>
        public static string Menu_List_Employee {
            get {
                return ResourceManager.GetString("Menu_List_Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Menu_List_Product.
        /// </summary>
        public static string Menu_List_Product {
            get {
                return ResourceManager.GetString("Menu_List_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Menu_List_Supplier.
        /// </summary>
        public static string Menu_List_Supplier {
            get {
                return ResourceManager.GetString("Menu_List_Supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Menu_Register.
        /// </summary>
        public static string Menu_Register {
            get {
                return ResourceManager.GetString("Menu_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Menu_Register_Client.
        /// </summary>
        public static string Menu_Register_Client {
            get {
                return ResourceManager.GetString("Menu_Register_Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Menu_Register_Company.
        /// </summary>
        public static string Menu_Register_Company {
            get {
                return ResourceManager.GetString("Menu_Register_Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Menu_Register_Employee.
        /// </summary>
        public static string Menu_Register_Employee {
            get {
                return ResourceManager.GetString("Menu_Register_Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Menu_Register_Product.
        /// </summary>
        public static string Menu_Register_Product {
            get {
                return ResourceManager.GetString("Menu_Register_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Menu_Register_Supplier.
        /// </summary>
        public static string Menu_Register_Supplier {
            get {
                return ResourceManager.GetString("Menu_Register_Supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Menu_Report.
        /// </summary>
        public static string Menu_Report {
            get {
                return ResourceManager.GetString("Menu_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Menu_Sales.
        /// </summary>
        public static string Menu_Sales {
            get {
                return ResourceManager.GetString("Menu_Sales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Menu_Sales_Alter.
        /// </summary>
        public static string Menu_Sales_Alter {
            get {
                return ResourceManager.GetString("Menu_Sales_Alter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Menu_Sales_History.
        /// </summary>
        public static string Menu_Sales_History {
            get {
                return ResourceManager.GetString("Menu_Sales_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Menu_Sales_New.
        /// </summary>
        public static string Menu_Sales_New {
            get {
                return ResourceManager.GetString("Menu_Sales_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Menu_Util.
        /// </summary>
        public static string Menu_Util {
            get {
                return ResourceManager.GetString("Menu_Util", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Menu_Util_Address.
        /// </summary>
        public static string Menu_Util_Address {
            get {
                return ResourceManager.GetString("Menu_Util_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Menu_Util_Comission.
        /// </summary>
        public static string Menu_Util_Comission {
            get {
                return ResourceManager.GetString("Menu_Util_Comission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Menu_Util_ContactInfo.
        /// </summary>
        public static string Menu_Util_ContactInfo {
            get {
                return ResourceManager.GetString("Menu_Util_ContactInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Menu_Util_Paycheck.
        /// </summary>
        public static string Menu_Util_Paycheck {
            get {
                return ResourceManager.GetString("Menu_Util_Paycheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Window_Title.
        /// </summary>
        public static string Window_Title {
            get {
                return ResourceManager.GetString("Window_Title", resourceCulture);
            }
        }
    }
}
