//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOB.Core.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LOB.Core.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Button_Cancel.
        /// </summary>
        public static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Button_Close.
        /// </summary>
        public static string Button_Close {
            get {
                return ResourceManager.GetString("Button_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Button_Confirm.
        /// </summary>
        public static string Button_Confirm {
            get {
                return ResourceManager.GetString("Button_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Button_ConfirmOp.
        /// </summary>
        public static string Button_ConfirmOp {
            get {
                return ResourceManager.GetString("Button_ConfirmOp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Command_AlterAddress.
        /// </summary>
        public static string Command_AlterAddress {
            get {
                return ResourceManager.GetString("Command_AlterAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Command_AlterBaseEntity.
        /// </summary>
        public static string Command_AlterBaseEntity {
            get {
                return ResourceManager.GetString("Command_AlterBaseEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Command_AlterCategory.
        /// </summary>
        public static string Command_AlterCategory {
            get {
                return ResourceManager.GetString("Command_AlterCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Command_AlterContactInfo.
        /// </summary>
        public static string Command_AlterContactInfo {
            get {
                return ResourceManager.GetString("Command_AlterContactInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Command_AlterCustomer.
        /// </summary>
        public static string Command_AlterCustomer {
            get {
                return ResourceManager.GetString("Command_AlterCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Command_AlterEmail.
        /// </summary>
        public static string Command_AlterEmail {
            get {
                return ResourceManager.GetString("Command_AlterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Command_AlterEmployee.
        /// </summary>
        public static string Command_AlterEmployee {
            get {
                return ResourceManager.GetString("Command_AlterEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Command_AlterLegalPerson.
        /// </summary>
        public static string Command_AlterLegalPerson {
            get {
                return ResourceManager.GetString("Command_AlterLegalPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Command_AlterNaturalPerson.
        /// </summary>
        public static string Command_AlterNaturalPerson {
            get {
                return ResourceManager.GetString("Command_AlterNaturalPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Command_AlterPayCheck.
        /// </summary>
        public static string Command_AlterPayCheck {
            get {
                return ResourceManager.GetString("Command_AlterPayCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Command_AlterPerson.
        /// </summary>
        public static string Command_AlterPerson {
            get {
                return ResourceManager.GetString("Command_AlterPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Command_AlterPhoneNumber.
        /// </summary>
        public static string Command_AlterPhoneNumber {
            get {
                return ResourceManager.GetString("Command_AlterPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Command_AlterProduct.
        /// </summary>
        public static string Command_AlterProduct {
            get {
                return ResourceManager.GetString("Command_AlterProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Command_AlterSale.
        /// </summary>
        public static string Command_AlterSale {
            get {
                return ResourceManager.GetString("Command_AlterSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Command_AlterService.
        /// </summary>
        public static string Command_AlterService {
            get {
                return ResourceManager.GetString("Command_AlterService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Command_ListAddress.
        /// </summary>
        public static string Command_ListAddress {
            get {
                return ResourceManager.GetString("Command_ListAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Command_ListBaseEntity.
        /// </summary>
        public static string Command_ListBaseEntity {
            get {
                return ResourceManager.GetString("Command_ListBaseEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Command_ListCategory.
        /// </summary>
        public static string Command_ListCategory {
            get {
                return ResourceManager.GetString("Command_ListCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Command_ListContactInfo.
        /// </summary>
        public static string Command_ListContactInfo {
            get {
                return ResourceManager.GetString("Command_ListContactInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Command_ListCustomer.
        /// </summary>
        public static string Command_ListCustomer {
            get {
                return ResourceManager.GetString("Command_ListCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Command_ListEmail.
        /// </summary>
        public static string Command_ListEmail {
            get {
                return ResourceManager.GetString("Command_ListEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Command_ListEmployee.
        /// </summary>
        public static string Command_ListEmployee {
            get {
                return ResourceManager.GetString("Command_ListEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Command_ListLegalPerson.
        /// </summary>
        public static string Command_ListLegalPerson {
            get {
                return ResourceManager.GetString("Command_ListLegalPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Command_ListNaturalPerson.
        /// </summary>
        public static string Command_ListNaturalPerson {
            get {
                return ResourceManager.GetString("Command_ListNaturalPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Command_ListOp.
        /// </summary>
        public static string Command_ListOp {
            get {
                return ResourceManager.GetString("Command_ListOp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Command_ListPayCheck.
        /// </summary>
        public static string Command_ListPayCheck {
            get {
                return ResourceManager.GetString("Command_ListPayCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Command_ListPerson.
        /// </summary>
        public static string Command_ListPerson {
            get {
                return ResourceManager.GetString("Command_ListPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Command_ListPhoneNumber.
        /// </summary>
        public static string Command_ListPhoneNumber {
            get {
                return ResourceManager.GetString("Command_ListPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Command_ListProduct.
        /// </summary>
        public static string Command_ListProduct {
            get {
                return ResourceManager.GetString("Command_ListProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Command_ListSale.
        /// </summary>
        public static string Command_ListSale {
            get {
                return ResourceManager.GetString("Command_ListSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Command_ListService.
        /// </summary>
        public static string Command_ListService {
            get {
                return ResourceManager.GetString("Command_ListService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Command_SellProduct.
        /// </summary>
        public static string Command_SellProduct {
            get {
                return ResourceManager.GetString("Command_SellProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Command_SellService.
        /// </summary>
        public static string Command_SellService {
            get {
                return ResourceManager.GetString("Command_SellService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Address.
        /// </summary>
        public static string Common_Address {
            get {
                return ResourceManager.GetString("Common_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Address_Active.
        /// </summary>
        public static string Common_Address_Active {
            get {
                return ResourceManager.GetString("Common_Address_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Address_Deprecated.
        /// </summary>
        public static string Common_Address_Deprecated {
            get {
                return ResourceManager.GetString("Common_Address_Deprecated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Address_Inactive.
        /// </summary>
        public static string Common_Address_Inactive {
            get {
                return ResourceManager.GetString("Common_Address_Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_AvailableInStore.
        /// </summary>
        public static string Common_AvailableInStore {
            get {
                return ResourceManager.GetString("Common_AvailableInStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_BirthDate.
        /// </summary>
        public static string Common_BirthDate {
            get {
                return ResourceManager.GetString("Common_BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Bonus.
        /// </summary>
        public static string Common_Bonus {
            get {
                return ResourceManager.GetString("Common_Bonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_BoughtHistory.
        /// </summary>
        public static string Common_BoughtHistory {
            get {
                return ResourceManager.GetString("Common_BoughtHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Category.
        /// </summary>
        public static string Common_Category {
            get {
                return ResourceManager.GetString("Common_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_City.
        /// </summary>
        public static string Common_City {
            get {
                return ResourceManager.GetString("Common_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_CnaeFiscal.
        /// </summary>
        public static string Common_CnaeFiscal {
            get {
                return ResourceManager.GetString("Common_CnaeFiscal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Cnpj.
        /// </summary>
        public static string Common_Cnpj {
            get {
                return ResourceManager.GetString("Common_Cnpj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Code.
        /// </summary>
        public static string Common_Code {
            get {
                return ResourceManager.GetString("Common_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Complement.
        /// </summary>
        public static string Common_Complement {
            get {
                return ResourceManager.GetString("Common_Complement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Contact.
        /// </summary>
        public static string Common_Contact {
            get {
                return ResourceManager.GetString("Common_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_ContactInfo.
        /// </summary>
        public static string Common_ContactInfo {
            get {
                return ResourceManager.GetString("Common_ContactInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_CorporateName.
        /// </summary>
        public static string Common_CorporateName {
            get {
                return ResourceManager.GetString("Common_CorporateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Country.
        /// </summary>
        public static string Common_Country {
            get {
                return ResourceManager.GetString("Common_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Cpf.
        /// </summary>
        public static string Common_Cpf {
            get {
                return ResourceManager.GetString("Common_Cpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_CurrentSalary.
        /// </summary>
        public static string Common_CurrentSalary {
            get {
                return ResourceManager.GetString("Common_CurrentSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Customer.
        /// </summary>
        public static string Common_Customer {
            get {
                return ResourceManager.GetString("Common_Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_CustomerOf.
        /// </summary>
        public static string Common_CustomerOf {
            get {
                return ResourceManager.GetString("Common_CustomerOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Date.
        /// </summary>
        public static string Common_Date {
            get {
                return ResourceManager.GetString("Common_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Default.
        /// </summary>
        public static string Common_Default {
            get {
                return ResourceManager.GetString("Common_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Description.
        /// </summary>
        public static string Common_Description {
            get {
                return ResourceManager.GetString("Common_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_District.
        /// </summary>
        public static string Common_District {
            get {
                return ResourceManager.GetString("Common_District", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Email.
        /// </summary>
        public static string Common_Email {
            get {
                return ResourceManager.GetString("Common_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Emails.
        /// </summary>
        public static string Common_Emails {
            get {
                return ResourceManager.GetString("Common_Emails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_FirstName.
        /// </summary>
        public static string Common_FirstName {
            get {
                return ResourceManager.GetString("Common_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_HireDate.
        /// </summary>
        public static string Common_HireDate {
            get {
                return ResourceManager.GetString("Common_HireDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Id.
        /// </summary>
        public static string Common_Id {
            get {
                return ResourceManager.GetString("Common_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Image.
        /// </summary>
        public static string Common_Image {
            get {
                return ResourceManager.GetString("Common_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_InscEstadual.
        /// </summary>
        public static string Common_InscEstadual {
            get {
                return ResourceManager.GetString("Common_InscEstadual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_InscMunicipal.
        /// </summary>
        public static string Common_InscMunicipal {
            get {
                return ResourceManager.GetString("Common_InscMunicipal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_LastName.
        /// </summary>
        public static string Common_LastName {
            get {
                return ResourceManager.GetString("Common_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Name.
        /// </summary>
        public static string Common_Name {
            get {
                return ResourceManager.GetString("Common_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_NickName.
        /// </summary>
        public static string Common_NickName {
            get {
                return ResourceManager.GetString("Common_NickName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Notes.
        /// </summary>
        public static string Common_Notes {
            get {
                return ResourceManager.GetString("Common_Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Number.
        /// </summary>
        public static string Common_Number {
            get {
                return ResourceManager.GetString("Common_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_PayCheck.
        /// </summary>
        public static string Common_PayCheck {
            get {
                return ResourceManager.GetString("Common_PayCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_PersonDetails.
        /// </summary>
        public static string Common_PersonDetails {
            get {
                return ResourceManager.GetString("Common_PersonDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_PersonType.
        /// </summary>
        public static string Common_PersonType {
            get {
                return ResourceManager.GetString("Common_PersonType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_PhoneNumber.
        /// </summary>
        public static string Common_PhoneNumber {
            get {
                return ResourceManager.GetString("Common_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_PhoneNumbers.
        /// </summary>
        public static string Common_PhoneNumbers {
            get {
                return ResourceManager.GetString("Common_PhoneNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Product.
        /// </summary>
        public static string Common_Product {
            get {
                return ResourceManager.GetString("Common_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Products.
        /// </summary>
        public static string Common_Products {
            get {
                return ResourceManager.GetString("Common_Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Ps.
        /// </summary>
        public static string Common_Ps {
            get {
                return ResourceManager.GetString("Common_Ps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_QuantityPerUnity.
        /// </summary>
        public static string Common_QuantityPerUnity {
            get {
                return ResourceManager.GetString("Common_QuantityPerUnity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Rg.
        /// </summary>
        public static string Common_Rg {
            get {
                return ResourceManager.GetString("Common_Rg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Search.
        /// </summary>
        public static string Common_Search {
            get {
                return ResourceManager.GetString("Common_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_State.
        /// </summary>
        public static string Common_State {
            get {
                return ResourceManager.GetString("Common_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Status.
        /// </summary>
        public static string Common_Status {
            get {
                return ResourceManager.GetString("Common_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Stores.
        /// </summary>
        public static string Common_Stores {
            get {
                return ResourceManager.GetString("Common_Stores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Street.
        /// </summary>
        public static string Common_Street {
            get {
                return ResourceManager.GetString("Common_Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_StreetNumber.
        /// </summary>
        public static string Common_StreetNumber {
            get {
                return ResourceManager.GetString("Common_StreetNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Suppliers.
        /// </summary>
        public static string Common_Suppliers {
            get {
                return ResourceManager.GetString("Common_Suppliers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Title.
        /// </summary>
        public static string Common_Title {
            get {
                return ResourceManager.GetString("Common_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_TotalValue.
        /// </summary>
        public static string Common_TotalValue {
            get {
                return ResourceManager.GetString("Common_TotalValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_TradingName.
        /// </summary>
        public static string Common_TradingName {
            get {
                return ResourceManager.GetString("Common_TradingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_UnitSalePrice.
        /// </summary>
        public static string Common_UnitSalePrice {
            get {
                return ResourceManager.GetString("Common_UnitSalePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_UnitsInStock.
        /// </summary>
        public static string Common_UnitsInStock {
            get {
                return ResourceManager.GetString("Common_UnitsInStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Website.
        /// </summary>
        public static string Common_Website {
            get {
                return ResourceManager.GetString("Common_Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_WorkInStore.
        /// </summary>
        public static string Common_WorkInStore {
            get {
                return ResourceManager.GetString("Common_WorkInStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_ZipCode.
        /// </summary>
        public static string Common_ZipCode {
            get {
                return ResourceManager.GetString("Common_ZipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Dao_Connecting.
        /// </summary>
        public static string Dao_Connecting {
            get {
                return ResourceManager.GetString("Dao_Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Dao_ConnectionFailed.
        /// </summary>
        public static string Dao_ConnectionFailed {
            get {
                return ResourceManager.GetString("Dao_ConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Dao_ConnectionSucessful.
        /// </summary>
        public static string Dao_ConnectionSucessful {
            get {
                return ResourceManager.GetString("Dao_ConnectionSucessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Dao_RequisitionFailed.
        /// </summary>
        public static string Dao_RequisitionFailed {
            get {
                return ResourceManager.GetString("Dao_RequisitionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Dao_RequisitionSucessful.
        /// </summary>
        public static string Dao_RequisitionSucessful {
            get {
                return ResourceManager.GetString("Dao_RequisitionSucessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Error_Field_Empty.
        /// </summary>
        public static string Error_Field_Empty {
            get {
                return ResourceManager.GetString("Error_Field_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Error_Field_IntOnly.
        /// </summary>
        public static string Error_Field_IntOnly {
            get {
                return ResourceManager.GetString("Error_Field_IntOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Error_Field_Necessary.
        /// </summary>
        public static string Error_Field_Necessary {
            get {
                return ResourceManager.GetString("Error_Field_Necessary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Error_Field_NotEmpty.
        /// </summary>
        public static string Error_Field_NotEmpty {
            get {
                return ResourceManager.GetString("Error_Field_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Error_Field_NotNecessary.
        /// </summary>
        public static string Error_Field_NotNecessary {
            get {
                return ResourceManager.GetString("Error_Field_NotNecessary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Error_Field_TooLong.
        /// </summary>
        public static string Error_Field_TooLong {
            get {
                return ResourceManager.GetString("Error_Field_TooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Error_Field_TooShort.
        /// </summary>
        public static string Error_Field_TooShort {
            get {
                return ResourceManager.GetString("Error_Field_TooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Error_Field_WrongFormat.
        /// </summary>
        public static string Error_Field_WrongFormat {
            get {
                return ResourceManager.GetString("Error_Field_WrongFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Error_Info.
        /// </summary>
        public static string Error_Info {
            get {
                return ResourceManager.GetString("Error_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Error_Internal.
        /// </summary>
        public static string Error_Internal {
            get {
                return ResourceManager.GetString("Error_Internal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Header_Alter_Address.
        /// </summary>
        public static string Header_Alter_Address {
            get {
                return ResourceManager.GetString("Header_Alter_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Header_Alter_BaseEntity.
        /// </summary>
        public static string Header_Alter_BaseEntity {
            get {
                return ResourceManager.GetString("Header_Alter_BaseEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Header_Alter_Category.
        /// </summary>
        public static string Header_Alter_Category {
            get {
                return ResourceManager.GetString("Header_Alter_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Header_Alter_ContactInfo.
        /// </summary>
        public static string Header_Alter_ContactInfo {
            get {
                return ResourceManager.GetString("Header_Alter_ContactInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Header_Alter_Customer.
        /// </summary>
        public static string Header_Alter_Customer {
            get {
                return ResourceManager.GetString("Header_Alter_Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Header_Alter_Email.
        /// </summary>
        public static string Header_Alter_Email {
            get {
                return ResourceManager.GetString("Header_Alter_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Header_Alter_Employee.
        /// </summary>
        public static string Header_Alter_Employee {
            get {
                return ResourceManager.GetString("Header_Alter_Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Header_Alter_LegalPerson.
        /// </summary>
        public static string Header_Alter_LegalPerson {
            get {
                return ResourceManager.GetString("Header_Alter_LegalPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Header_Alter_NaturalPerson.
        /// </summary>
        public static string Header_Alter_NaturalPerson {
            get {
                return ResourceManager.GetString("Header_Alter_NaturalPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Header_Alter_PayCheck.
        /// </summary>
        public static string Header_Alter_PayCheck {
            get {
                return ResourceManager.GetString("Header_Alter_PayCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Header_Alter_Person.
        /// </summary>
        public static string Header_Alter_Person {
            get {
                return ResourceManager.GetString("Header_Alter_Person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Header_Alter_PhoneNumber.
        /// </summary>
        public static string Header_Alter_PhoneNumber {
            get {
                return ResourceManager.GetString("Header_Alter_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Header_Alter_Product.
        /// </summary>
        public static string Header_Alter_Product {
            get {
                return ResourceManager.GetString("Header_Alter_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Header_Alter_Sale.
        /// </summary>
        public static string Header_Alter_Sale {
            get {
                return ResourceManager.GetString("Header_Alter_Sale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Header_Alter_Service.
        /// </summary>
        public static string Header_Alter_Service {
            get {
                return ResourceManager.GetString("Header_Alter_Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Header_List_BaseEntity.
        /// </summary>
        public static string Header_List_BaseEntity {
            get {
                return ResourceManager.GetString("Header_List_BaseEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Header_List_Category.
        /// </summary>
        public static string Header_List_Category {
            get {
                return ResourceManager.GetString("Header_List_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Header_List_Customer.
        /// </summary>
        public static string Header_List_Customer {
            get {
                return ResourceManager.GetString("Header_List_Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Header_List_Email.
        /// </summary>
        public static string Header_List_Email {
            get {
                return ResourceManager.GetString("Header_List_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Header_List_Employee.
        /// </summary>
        public static string Header_List_Employee {
            get {
                return ResourceManager.GetString("Header_List_Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Header_List_Op.
        /// </summary>
        public static string Header_List_Op {
            get {
                return ResourceManager.GetString("Header_List_Op", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Header_List_PhoneNumber.
        /// </summary>
        public static string Header_List_PhoneNumber {
            get {
                return ResourceManager.GetString("Header_List_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Header_List_Product.
        /// </summary>
        public static string Header_List_Product {
            get {
                return ResourceManager.GetString("Header_List_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Header_ListService.
        /// </summary>
        public static string Header_ListService {
            get {
                return ResourceManager.GetString("Header_ListService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Header_Main_Busy.
        /// </summary>
        public static string Header_Main_Busy {
            get {
                return ResourceManager.GetString("Header_Main_Busy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Header_Main_Column.
        /// </summary>
        public static string Header_Main_Column {
            get {
                return ResourceManager.GetString("Header_Main_Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Header_Main_Header.
        /// </summary>
        public static string Header_Main_Header {
            get {
                return ResourceManager.GetString("Header_Main_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Header_Main_Message.
        /// </summary>
        public static string Header_Main_Message {
            get {
                return ResourceManager.GetString("Header_Main_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Header_Sell_Product.
        /// </summary>
        public static string Header_Sell_Product {
            get {
                return ResourceManager.GetString("Header_Sell_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Header_Sell_Service.
        /// </summary>
        public static string Header_Sell_Service {
            get {
                return ResourceManager.GetString("Header_Sell_Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Menu_File.
        /// </summary>
        public static string Menu_File {
            get {
                return ResourceManager.GetString("Menu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Menu_Quit.
        /// </summary>
        public static string Menu_File_Quit {
            get {
                return ResourceManager.GetString("Menu_File_Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Menu_Save.
        /// </summary>
        public static string Menu_File_Save {
            get {
                return ResourceManager.GetString("Menu_File_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Menu_List.
        /// </summary>
        public static string Menu_List {
            get {
                return ResourceManager.GetString("Menu_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Menu_List_Client.
        /// </summary>
        public static string Menu_List_Client {
            get {
                return ResourceManager.GetString("Menu_List_Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Menu_List_Company.
        /// </summary>
        public static string Menu_List_Company {
            get {
                return ResourceManager.GetString("Menu_List_Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Menu_List_Employee.
        /// </summary>
        public static string Menu_List_Employee {
            get {
                return ResourceManager.GetString("Menu_List_Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Menu_List_Product.
        /// </summary>
        public static string Menu_List_Product {
            get {
                return ResourceManager.GetString("Menu_List_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Menu_List_Supplier.
        /// </summary>
        public static string Menu_List_Supplier {
            get {
                return ResourceManager.GetString("Menu_List_Supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Menu_Register.
        /// </summary>
        public static string Menu_Register {
            get {
                return ResourceManager.GetString("Menu_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Menu_Register_Client.
        /// </summary>
        public static string Menu_Register_Client {
            get {
                return ResourceManager.GetString("Menu_Register_Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Menu_Register_Company.
        /// </summary>
        public static string Menu_Register_Company {
            get {
                return ResourceManager.GetString("Menu_Register_Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Menu_Register_Employee.
        /// </summary>
        public static string Menu_Register_Employee {
            get {
                return ResourceManager.GetString("Menu_Register_Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Menu_Register_Product.
        /// </summary>
        public static string Menu_Register_Product {
            get {
                return ResourceManager.GetString("Menu_Register_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Menu_Register_Supplier.
        /// </summary>
        public static string Menu_Register_Supplier {
            get {
                return ResourceManager.GetString("Menu_Register_Supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Menu_Report.
        /// </summary>
        public static string Menu_Report {
            get {
                return ResourceManager.GetString("Menu_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Menu_Sales.
        /// </summary>
        public static string Menu_Sales {
            get {
                return ResourceManager.GetString("Menu_Sales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Menu_Sales_Alter.
        /// </summary>
        public static string Menu_Sales_Alter {
            get {
                return ResourceManager.GetString("Menu_Sales_Alter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Menu_Sales_History.
        /// </summary>
        public static string Menu_Sales_History {
            get {
                return ResourceManager.GetString("Menu_Sales_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Menu_Sales_New.
        /// </summary>
        public static string Menu_Sales_New {
            get {
                return ResourceManager.GetString("Menu_Sales_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Menu_Util.
        /// </summary>
        public static string Menu_Util {
            get {
                return ResourceManager.GetString("Menu_Util", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Menu_Util_Address.
        /// </summary>
        public static string Menu_Util_Address {
            get {
                return ResourceManager.GetString("Menu_Util_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Menu_Util_Comission.
        /// </summary>
        public static string Menu_Util_Comission {
            get {
                return ResourceManager.GetString("Menu_Util_Comission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Menu_Util_ContactInfo.
        /// </summary>
        public static string Menu_Util_ContactInfo {
            get {
                return ResourceManager.GetString("Menu_Util_ContactInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Menu_Util_Paycheck.
        /// </summary>
        public static string Menu_Util_Paycheck {
            get {
                return ResourceManager.GetString("Menu_Util_Paycheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Tab_Hide.
        /// </summary>
        public static string Tab_Hide {
            get {
                return ResourceManager.GetString("Tab_Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @ToolTip_AlterCustomer.
        /// </summary>
        public static string ToolTip_AlterCustomer {
            get {
                return ResourceManager.GetString("ToolTip_AlterCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @ToolTip_Clear.
        /// </summary>
        public static string ToolTip_Clear {
            get {
                return ResourceManager.GetString("ToolTip_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @ToolTip_Close.
        /// </summary>
        public static string ToolTip_Close {
            get {
                return ResourceManager.GetString("ToolTip_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @ToolTip_Code.
        /// </summary>
        public static string ToolTip_Code {
            get {
                return ResourceManager.GetString("ToolTip_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @ToolTip_Operations.
        /// </summary>
        public static string ToolTip_Operations {
            get {
                return ResourceManager.GetString("ToolTip_Operations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @ToolTip_QuickSearch.
        /// </summary>
        public static string ToolTip_QuickSearch {
            get {
                return ResourceManager.GetString("ToolTip_QuickSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @ToolTip_Sales.
        /// </summary>
        public static string ToolTip_Sales {
            get {
                return ResourceManager.GetString("ToolTip_Sales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Window_Title.
        /// </summary>
        public static string Window_Title {
            get {
                return ResourceManager.GetString("Window_Title", resourceCulture);
            }
        }
    }
}
