//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOB.Core.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LOB.Core.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @App_License_Information.
        /// </summary>
        public static string App_License_Information {
            get {
                return ResourceManager.GetString("App_License_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Command_AddAddress.
        /// </summary>
        public static string Command_Add_Address {
            get {
                return ResourceManager.GetString("Command_Add_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Command_AddBaseEntity.
        /// </summary>
        public static string Command_Add_BaseEntity {
            get {
                return ResourceManager.GetString("Command_Add_BaseEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Command_AddCategory.
        /// </summary>
        public static string Command_Add_Category {
            get {
                return ResourceManager.GetString("Command_Add_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Command_AddContactInfo.
        /// </summary>
        public static string Command_Add_ContactInfo {
            get {
                return ResourceManager.GetString("Command_Add_ContactInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Command_AddCustomer.
        /// </summary>
        public static string Command_Add_Customer {
            get {
                return ResourceManager.GetString("Command_Add_Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Command_AddEmail.
        /// </summary>
        public static string Command_Add_Email {
            get {
                return ResourceManager.GetString("Command_Add_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Command_AddEmployee.
        /// </summary>
        public static string Command_Add_Employee {
            get {
                return ResourceManager.GetString("Command_Add_Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Command_AddLegalPerson.
        /// </summary>
        public static string Command_Add_LegalPerson {
            get {
                return ResourceManager.GetString("Command_Add_LegalPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Command_AddNaturalPerson.
        /// </summary>
        public static string Command_Add_NaturalPerson {
            get {
                return ResourceManager.GetString("Command_Add_NaturalPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Command_AddPayCheck.
        /// </summary>
        public static string Command_Add_PayCheck {
            get {
                return ResourceManager.GetString("Command_Add_PayCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Command_AddPerson.
        /// </summary>
        public static string Command_Add_Person {
            get {
                return ResourceManager.GetString("Command_Add_Person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Command_AddPhoneNumber.
        /// </summary>
        public static string Command_Add_PhoneNumber {
            get {
                return ResourceManager.GetString("Command_Add_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Command_AddProduct.
        /// </summary>
        public static string Command_Add_Product {
            get {
                return ResourceManager.GetString("Command_Add_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Command_AddSale.
        /// </summary>
        public static string Command_Add_Sale {
            get {
                return ResourceManager.GetString("Command_Add_Sale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Command_AddService.
        /// </summary>
        public static string Command_Add_Service {
            get {
                return ResourceManager.GetString("Command_Add_Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Command_ListAddress.
        /// </summary>
        public static string Command_List_Address {
            get {
                return ResourceManager.GetString("Command_List_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Command_ListBaseEntity.
        /// </summary>
        public static string Command_List_BaseEntity {
            get {
                return ResourceManager.GetString("Command_List_BaseEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Command_ListCategory.
        /// </summary>
        public static string Command_List_Category {
            get {
                return ResourceManager.GetString("Command_List_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Command_ListContactInfo.
        /// </summary>
        public static string Command_List_ContactInfo {
            get {
                return ResourceManager.GetString("Command_List_ContactInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Command_ListCustomer.
        /// </summary>
        public static string Command_List_Customer {
            get {
                return ResourceManager.GetString("Command_List_Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Command_ListEmail.
        /// </summary>
        public static string Command_List_Email {
            get {
                return ResourceManager.GetString("Command_List_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Command_ListEmployee.
        /// </summary>
        public static string Command_List_Employee {
            get {
                return ResourceManager.GetString("Command_List_Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Command_ListLegalPerson.
        /// </summary>
        public static string Command_List_LegalPerson {
            get {
                return ResourceManager.GetString("Command_List_LegalPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Command_ListNaturalPerson.
        /// </summary>
        public static string Command_List_NaturalPerson {
            get {
                return ResourceManager.GetString("Command_List_NaturalPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Command_ListOp.
        /// </summary>
        public static string Command_List_Op {
            get {
                return ResourceManager.GetString("Command_List_Op", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Command_ListPayCheck.
        /// </summary>
        public static string Command_List_PayCheck {
            get {
                return ResourceManager.GetString("Command_List_PayCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Command_ListPerson.
        /// </summary>
        public static string Command_List_Person {
            get {
                return ResourceManager.GetString("Command_List_Person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Command_ListPhoneNumber.
        /// </summary>
        public static string Command_List_PhoneNumber {
            get {
                return ResourceManager.GetString("Command_List_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Command_ListProduct.
        /// </summary>
        public static string Command_List_Product {
            get {
                return ResourceManager.GetString("Command_List_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Command_ListSale.
        /// </summary>
        public static string Command_List_Sale {
            get {
                return ResourceManager.GetString("Command_List_Sale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Command_ListService.
        /// </summary>
        public static string Command_List_Service {
            get {
                return ResourceManager.GetString("Command_List_Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Command_SellProduct.
        /// </summary>
        public static string Command_Sell_Product {
            get {
                return ResourceManager.GetString("Command_Sell_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Command_SellService.
        /// </summary>
        public static string Command_Sell_Service {
            get {
                return ResourceManager.GetString("Command_Sell_Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Command_UpdateAddress.
        /// </summary>
        public static string Command_Update_Address {
            get {
                return ResourceManager.GetString("Command_Update_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Command_UpdateBaseEntity.
        /// </summary>
        public static string Command_Update_BaseEntity {
            get {
                return ResourceManager.GetString("Command_Update_BaseEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Command_UpdateCategory.
        /// </summary>
        public static string Command_Update_Category {
            get {
                return ResourceManager.GetString("Command_Update_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Command_UpdateContactInfo.
        /// </summary>
        public static string Command_Update_ContactInfo {
            get {
                return ResourceManager.GetString("Command_Update_ContactInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Command_UpdateCustomer.
        /// </summary>
        public static string Command_Update_Customer {
            get {
                return ResourceManager.GetString("Command_Update_Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Command_UpdateEmail.
        /// </summary>
        public static string Command_Update_Email {
            get {
                return ResourceManager.GetString("Command_Update_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Command_UpdateEmployee.
        /// </summary>
        public static string Command_Update_Employee {
            get {
                return ResourceManager.GetString("Command_Update_Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Command_UpdateLegalPerson.
        /// </summary>
        public static string Command_Update_LegalPerson {
            get {
                return ResourceManager.GetString("Command_Update_LegalPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Command_UpdateNaturalPerson.
        /// </summary>
        public static string Command_Update_NaturalPerson {
            get {
                return ResourceManager.GetString("Command_Update_NaturalPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Command_UpdatePayCheck.
        /// </summary>
        public static string Command_Update_PayCheck {
            get {
                return ResourceManager.GetString("Command_Update_PayCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Command_UpdatePerson.
        /// </summary>
        public static string Command_Update_Person {
            get {
                return ResourceManager.GetString("Command_Update_Person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Command_UpdatePhoneNumber.
        /// </summary>
        public static string Command_Update_PhoneNumber {
            get {
                return ResourceManager.GetString("Command_Update_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Command_UpdateProduct.
        /// </summary>
        public static string Command_Update_Product {
            get {
                return ResourceManager.GetString("Command_Update_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Command_UpdateSale.
        /// </summary>
        public static string Command_Update_Sale {
            get {
                return ResourceManager.GetString("Command_Update_Sale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Command_UpdateService.
        /// </summary>
        public static string Command_Update_Service {
            get {
                return ResourceManager.GetString("Command_Update_Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Add.
        /// </summary>
        public static string Common_Add {
            get {
                return ResourceManager.GetString("Common_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Address.
        /// </summary>
        public static string Common_Address {
            get {
                return ResourceManager.GetString("Common_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Address_Active.
        /// </summary>
        public static string Common_Address_Active {
            get {
                return ResourceManager.GetString("Common_Address_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Address_Deprecated.
        /// </summary>
        public static string Common_Address_Deprecated {
            get {
                return ResourceManager.GetString("Common_Address_Deprecated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Address_Inactive.
        /// </summary>
        public static string Common_Address_Inactive {
            get {
                return ResourceManager.GetString("Common_Address_Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Attention.
        /// </summary>
        public static string Common_Attention {
            get {
                return ResourceManager.GetString("Common_Attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_AvailableInStore.
        /// </summary>
        public static string Common_AvailableInStore {
            get {
                return ResourceManager.GetString("Common_AvailableInStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_BirthDate.
        /// </summary>
        public static string Common_BirthDate {
            get {
                return ResourceManager.GetString("Common_BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Bonus.
        /// </summary>
        public static string Common_Bonus {
            get {
                return ResourceManager.GetString("Common_Bonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_BoughtHistory.
        /// </summary>
        public static string Common_BoughtHistory {
            get {
                return ResourceManager.GetString("Common_BoughtHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Cancel.
        /// </summary>
        public static string Common_Cancel {
            get {
                return ResourceManager.GetString("Common_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Category.
        /// </summary>
        public static string Common_Category {
            get {
                return ResourceManager.GetString("Common_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_CFOP.
        /// </summary>
        public static string Common_CFOP {
            get {
                return ResourceManager.GetString("Common_CFOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_City.
        /// </summary>
        public static string Common_City {
            get {
                return ResourceManager.GetString("Common_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Close.
        /// </summary>
        public static string Common_Close {
            get {
                return ResourceManager.GetString("Common_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_CnaeFiscal.
        /// </summary>
        public static string Common_CnaeFiscal {
            get {
                return ResourceManager.GetString("Common_CnaeFiscal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Cnpj.
        /// </summary>
        public static string Common_Cnpj {
            get {
                return ResourceManager.GetString("Common_Cnpj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_CodBarras.
        /// </summary>
        public static string Common_CodBarras {
            get {
                return ResourceManager.GetString("Common_CodBarras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Code.
        /// </summary>
        public static string Common_Code {
            get {
                return ResourceManager.GetString("Common_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Complement.
        /// </summary>
        public static string Common_Complement {
            get {
                return ResourceManager.GetString("Common_Complement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Confirm.
        /// </summary>
        public static string Common_Confirm {
            get {
                return ResourceManager.GetString("Common_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Confirm_Add.
        /// </summary>
        public static string Common_Confirm_Add {
            get {
                return ResourceManager.GetString("Common_Confirm_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Confirm_Command.
        /// </summary>
        public static string Common_Confirm_Command {
            get {
                return ResourceManager.GetString("Common_Confirm_Command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Confirm_Delete.
        /// </summary>
        public static string Common_Confirm_Delete {
            get {
                return ResourceManager.GetString("Common_Confirm_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Confirm_List.
        /// </summary>
        public static string Common_Confirm_List {
            get {
                return ResourceManager.GetString("Common_Confirm_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Confirm_Op.
        /// </summary>
        public static string Common_Confirm_Op {
            get {
                return ResourceManager.GetString("Common_Confirm_Op", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Confirm_QuickSearch.
        /// </summary>
        public static string Common_Confirm_QuickSearch {
            get {
                return ResourceManager.GetString("Common_Confirm_QuickSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Confirm_Update.
        /// </summary>
        public static string Common_Confirm_Update {
            get {
                return ResourceManager.GetString("Common_Confirm_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Contact.
        /// </summary>
        public static string Common_Contact {
            get {
                return ResourceManager.GetString("Common_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_ContactInfo.
        /// </summary>
        public static string Common_ContactInfo {
            get {
                return ResourceManager.GetString("Common_ContactInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_CorporateName.
        /// </summary>
        public static string Common_CorporateName {
            get {
                return ResourceManager.GetString("Common_CorporateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Country.
        /// </summary>
        public static string Common_Country {
            get {
                return ResourceManager.GetString("Common_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_County.
        /// </summary>
        public static string Common_County {
            get {
                return ResourceManager.GetString("Common_County", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Cpf.
        /// </summary>
        public static string Common_Cpf {
            get {
                return ResourceManager.GetString("Common_Cpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_CurrentSalary.
        /// </summary>
        public static string Common_CurrentSalary {
            get {
                return ResourceManager.GetString("Common_CurrentSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Customer.
        /// </summary>
        public static string Common_Customer {
            get {
                return ResourceManager.GetString("Common_Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_CustomerOf.
        /// </summary>
        public static string Common_CustomerOf {
            get {
                return ResourceManager.GetString("Common_CustomerOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Date.
        /// </summary>
        public static string Common_Date {
            get {
                return ResourceManager.GetString("Common_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Default.
        /// </summary>
        public static string Common_Default {
            get {
                return ResourceManager.GetString("Common_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Delete.
        /// </summary>
        public static string Common_Delete {
            get {
                return ResourceManager.GetString("Common_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Description.
        /// </summary>
        public static string Common_Description {
            get {
                return ResourceManager.GetString("Common_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Detail.
        /// </summary>
        public static string Common_Detail {
            get {
                return ResourceManager.GetString("Common_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Details.
        /// </summary>
        public static string Common_Details {
            get {
                return ResourceManager.GetString("Common_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_District.
        /// </summary>
        public static string Common_District {
            get {
                return ResourceManager.GetString("Common_District", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Edit.
        /// </summary>
        public static string Common_Edit {
            get {
                return ResourceManager.GetString("Common_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Email.
        /// </summary>
        public static string Common_Email {
            get {
                return ResourceManager.GetString("Common_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Emails.
        /// </summary>
        public static string Common_Emails {
            get {
                return ResourceManager.GetString("Common_Emails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Error.
        /// </summary>
        public static string Common_Error {
            get {
                return ResourceManager.GetString("Common_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Exclude.
        /// </summary>
        public static string Common_Exclude {
            get {
                return ResourceManager.GetString("Common_Exclude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Field.
        /// </summary>
        public static string Common_Field {
            get {
                return ResourceManager.GetString("Common_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Filter.
        /// </summary>
        public static string Common_Filter {
            get {
                return ResourceManager.GetString("Common_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_FirstName.
        /// </summary>
        public static string Common_FirstName {
            get {
                return ResourceManager.GetString("Common_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Fix.
        /// </summary>
        public static string Common_Fix {
            get {
                return ResourceManager.GetString("Common_Fix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_HireDate.
        /// </summary>
        public static string Common_HireDate {
            get {
                return ResourceManager.GetString("Common_HireDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Id.
        /// </summary>
        public static string Common_Id {
            get {
                return ResourceManager.GetString("Common_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Image.
        /// </summary>
        public static string Common_Image {
            get {
                return ResourceManager.GetString("Common_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Include.
        /// </summary>
        public static string Common_Include {
            get {
                return ResourceManager.GetString("Common_Include", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Information.
        /// </summary>
        public static string Common_Information {
            get {
                return ResourceManager.GetString("Common_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Initialized.
        /// </summary>
        public static string Common_Initialized {
            get {
                return ResourceManager.GetString("Common_Initialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Initializing.
        /// </summary>
        public static string Common_Initializing {
            get {
                return ResourceManager.GetString("Common_Initializing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_InscEstadual.
        /// </summary>
        public static string Common_InscEstadual {
            get {
                return ResourceManager.GetString("Common_InscEstadual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_InscMunicipal.
        /// </summary>
        public static string Common_InscMunicipal {
            get {
                return ResourceManager.GetString("Common_InscMunicipal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_LastName.
        /// </summary>
        public static string Common_LastName {
            get {
                return ResourceManager.GetString("Common_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_License.
        /// </summary>
        public static string Common_License {
            get {
                return ResourceManager.GetString("Common_License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Message.
        /// </summary>
        public static string Common_Message {
            get {
                return ResourceManager.GetString("Common_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Name.
        /// </summary>
        public static string Common_Name {
            get {
                return ResourceManager.GetString("Common_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_NCM.
        /// </summary>
        public static string Common_NCM {
            get {
                return ResourceManager.GetString("Common_NCM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_NickName.
        /// </summary>
        public static string Common_NickName {
            get {
                return ResourceManager.GetString("Common_NickName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Notes.
        /// </summary>
        public static string Common_Notes {
            get {
                return ResourceManager.GetString("Common_Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Number.
        /// </summary>
        public static string Common_Number {
            get {
                return ResourceManager.GetString("Common_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_OK.
        /// </summary>
        public static string Common_OK {
            get {
                return ResourceManager.GetString("Common_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_PayCheck.
        /// </summary>
        public static string Common_PayCheck {
            get {
                return ResourceManager.GetString("Common_PayCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_PersonDetails.
        /// </summary>
        public static string Common_PersonDetails {
            get {
                return ResourceManager.GetString("Common_PersonDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_PersonType.
        /// </summary>
        public static string Common_PersonType {
            get {
                return ResourceManager.GetString("Common_PersonType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_PhoneNumber.
        /// </summary>
        public static string Common_PhoneNumber {
            get {
                return ResourceManager.GetString("Common_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_PhoneNumbers.
        /// </summary>
        public static string Common_PhoneNumbers {
            get {
                return ResourceManager.GetString("Common_PhoneNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Product.
        /// </summary>
        public static string Common_Product {
            get {
                return ResourceManager.GetString("Common_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Products.
        /// </summary>
        public static string Common_Products {
            get {
                return ResourceManager.GetString("Common_Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Ps.
        /// </summary>
        public static string Common_Ps {
            get {
                return ResourceManager.GetString("Common_Ps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_QuantityPerUnity.
        /// </summary>
        public static string Common_QuantityPerUnity {
            get {
                return ResourceManager.GetString("Common_QuantityPerUnity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Report.
        /// </summary>
        public static string Common_Report {
            get {
                return ResourceManager.GetString("Common_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Rg.
        /// </summary>
        public static string Common_Rg {
            get {
                return ResourceManager.GetString("Common_Rg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Rg_Uf.
        /// </summary>
        public static string Common_Rg_Uf {
            get {
                return ResourceManager.GetString("Common_Rg_Uf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Search.
        /// </summary>
        public static string Common_Search {
            get {
                return ResourceManager.GetString("Common_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Severity.
        /// </summary>
        public static string Common_Severity {
            get {
                return ResourceManager.GetString("Common_Severity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Shipper.
        /// </summary>
        public static string Common_Shipper {
            get {
                return ResourceManager.GetString("Common_Shipper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_SpeakWith.
        /// </summary>
        public static string Common_SpeakWith {
            get {
                return ResourceManager.GetString("Common_SpeakWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_State.
        /// </summary>
        public static string Common_State {
            get {
                return ResourceManager.GetString("Common_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Status.
        /// </summary>
        public static string Common_Status {
            get {
                return ResourceManager.GetString("Common_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Stores.
        /// </summary>
        public static string Common_Stores {
            get {
                return ResourceManager.GetString("Common_Stores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Street.
        /// </summary>
        public static string Common_Street {
            get {
                return ResourceManager.GetString("Common_Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_StreetNumber.
        /// </summary>
        public static string Common_StreetNumber {
            get {
                return ResourceManager.GetString("Common_StreetNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Suppliers.
        /// </summary>
        public static string Common_Suppliers {
            get {
                return ResourceManager.GetString("Common_Suppliers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Tab_Hide.
        /// </summary>
        public static string Common_Tab_Hide {
            get {
                return ResourceManager.GetString("Common_Tab_Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Title.
        /// </summary>
        public static string Common_Title {
            get {
                return ResourceManager.GetString("Common_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_TotalValue.
        /// </summary>
        public static string Common_TotalValue {
            get {
                return ResourceManager.GetString("Common_TotalValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Town.
        /// </summary>
        public static string Common_Town {
            get {
                return ResourceManager.GetString("Common_Town", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_TradingName.
        /// </summary>
        public static string Common_TradingName {
            get {
                return ResourceManager.GetString("Common_TradingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Uf.
        /// </summary>
        public static string Common_Uf {
            get {
                return ResourceManager.GetString("Common_Uf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_UnitSalePrice.
        /// </summary>
        public static string Common_UnitSalePrice {
            get {
                return ResourceManager.GetString("Common_UnitSalePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_UnitsInStock.
        /// </summary>
        public static string Common_UnitsInStock {
            get {
                return ResourceManager.GetString("Common_UnitsInStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Warning.
        /// </summary>
        public static string Common_Warning {
            get {
                return ResourceManager.GetString("Common_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Website.
        /// </summary>
        public static string Common_Website {
            get {
                return ResourceManager.GetString("Common_Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_WorkInStore.
        /// </summary>
        public static string Common_WorkInStore {
            get {
                return ResourceManager.GetString("Common_WorkInStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_ZipCode.
        /// </summary>
        public static string Common_ZipCode {
            get {
                return ResourceManager.GetString("Common_ZipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Notification_Connecting.
        /// </summary>
        public static string Notification_Connecting {
            get {
                return ResourceManager.GetString("Notification_Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Notification_ConnectionFailed.
        /// </summary>
        public static string Notification_ConnectionFailed {
            get {
                return ResourceManager.GetString("Notification_ConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Notification_ConnectionSucessful.
        /// </summary>
        public static string Notification_ConnectionSucessful {
            get {
                return ResourceManager.GetString("Notification_ConnectionSucessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Notification_Dao_Conected.
        /// </summary>
        public static string Notification_Dao_Conected {
            get {
                return ResourceManager.GetString("Notification_Dao_Conected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Notification_Dao_Connecting.
        /// </summary>
        public static string Notification_Dao_Connecting {
            get {
                return ResourceManager.GetString("Notification_Dao_Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Notification_Dao_Connecting_Failed.
        /// </summary>
        public static string Notification_Dao_Connecting_Failed {
            get {
                return ResourceManager.GetString("Notification_Dao_Connecting_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Notification_Dao_ConnectionFailed.
        /// </summary>
        public static string Notification_Dao_ConnectionFailed {
            get {
                return ResourceManager.GetString("Notification_Dao_ConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Notification_Dao_ConnectionSucessful.
        /// </summary>
        public static string Notification_Dao_ConnectionSucessful {
            get {
                return ResourceManager.GetString("Notification_Dao_ConnectionSucessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Notification_Dao_RequisitionFailed.
        /// </summary>
        public static string Notification_Dao_RequisitionFailed {
            get {
                return ResourceManager.GetString("Notification_Dao_RequisitionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Notification_Dao_RequisitionSucessful.
        /// </summary>
        public static string Notification_Dao_RequisitionSucessful {
            get {
                return ResourceManager.GetString("Notification_Dao_RequisitionSucessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Notification_Dao_Transaction_AlreadyActivated.
        /// </summary>
        public static string Notification_Dao_Transaction_AlreadyActivated {
            get {
                return ResourceManager.GetString("Notification_Dao_Transaction_AlreadyActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Notification_Dao_Transaction_AlreadyInitialized.
        /// </summary>
        public static string Notification_Dao_Transaction_AlreadyInitialized {
            get {
                return ResourceManager.GetString("Notification_Dao_Transaction_AlreadyInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Notification_Dao_Transaction_NotActivated.
        /// </summary>
        public static string Notification_Dao_Transaction_NotActivated {
            get {
                return ResourceManager.GetString("Notification_Dao_Transaction_NotActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Notification_Dao_Transaction_NotInitialized.
        /// </summary>
        public static string Notification_Dao_Transaction_NotInitialized {
            get {
                return ResourceManager.GetString("Notification_Dao_Transaction_NotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Notification_Field_Add.
        /// </summary>
        public static string Notification_Field_Add {
            get {
                return ResourceManager.GetString("Notification_Field_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Notification_Field_Added.
        /// </summary>
        public static string Notification_Field_Added {
            get {
                return ResourceManager.GetString("Notification_Field_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Notification_Field_Adding.
        /// </summary>
        public static string Notification_Field_Adding {
            get {
                return ResourceManager.GetString("Notification_Field_Adding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Notification_Field_Attention.
        /// </summary>
        public static string Notification_Field_Attention {
            get {
                return ResourceManager.GetString("Notification_Field_Attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Notification_Field_DateInvalid.
        /// </summary>
        public static string Notification_Field_DateInvalid {
            get {
                return ResourceManager.GetString("Notification_Field_DateInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Notification_Field_DateTooEarly.
        /// </summary>
        public static string Notification_Field_DateTooEarly {
            get {
                return ResourceManager.GetString("Notification_Field_DateTooEarly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Notification_Field_DateTooLate.
        /// </summary>
        public static string Notification_Field_DateTooLate {
            get {
                return ResourceManager.GetString("Notification_Field_DateTooLate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Notification_Field_Delete.
        /// </summary>
        public static string Notification_Field_Delete {
            get {
                return ResourceManager.GetString("Notification_Field_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Notification_Field_Deleted.
        /// </summary>
        public static string Notification_Field_Deleted {
            get {
                return ResourceManager.GetString("Notification_Field_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Notification_Field_Deleting.
        /// </summary>
        public static string Notification_Field_Deleting {
            get {
                return ResourceManager.GetString("Notification_Field_Deleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Notification_Field_Deprecated.
        /// </summary>
        public static string Notification_Field_Deprecated {
            get {
                return ResourceManager.GetString("Notification_Field_Deprecated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Notification_Field_Empty.
        /// </summary>
        public static string Notification_Field_Empty {
            get {
                return ResourceManager.GetString("Notification_Field_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Notification_ErrorInField.
        /// </summary>
        public static string Notification_Field_Error {
            get {
                return ResourceManager.GetString("Notification_Field_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Notification_Field_Filtering.
        /// </summary>
        public static string Notification_Field_Filtering {
            get {
                return ResourceManager.GetString("Notification_Field_Filtering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Notification_Field_Information.
        /// </summary>
        public static string Notification_Field_Information {
            get {
                return ResourceManager.GetString("Notification_Field_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Notification_Field_IntOnly.
        /// </summary>
        public static string Notification_Field_IntOnly {
            get {
                return ResourceManager.GetString("Notification_Field_IntOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Notification_Field_Invalid.
        /// </summary>
        public static string Notification_Field_Invalid {
            get {
                return ResourceManager.GetString("Notification_Field_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Notification_Field_Listed.
        /// </summary>
        public static string Notification_Field_Listed {
            get {
                return ResourceManager.GetString("Notification_Field_Listed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Notification_Field_Listing.
        /// </summary>
        public static string Notification_Field_Listing {
            get {
                return ResourceManager.GetString("Notification_Field_Listing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Notification_Field_Necessary.
        /// </summary>
        public static string Notification_Field_Necessary {
            get {
                return ResourceManager.GetString("Notification_Field_Necessary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Notification_Field_Negative.
        /// </summary>
        public static string Notification_Field_Negative {
            get {
                return ResourceManager.GetString("Notification_Field_Negative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Notification_Field_Nescessary.
        /// </summary>
        public static string Notification_Field_Nescessary {
            get {
                return ResourceManager.GetString("Notification_Field_Nescessary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Notification_Field_NotEmpty.
        /// </summary>
        public static string Notification_Field_NotEmpty {
            get {
                return ResourceManager.GetString("Notification_Field_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Notification_Field_NotNecessary.
        /// </summary>
        public static string Notification_Field_NotNecessary {
            get {
                return ResourceManager.GetString("Notification_Field_NotNecessary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Notification_Field_Positive.
        /// </summary>
        public static string Notification_Field_Positive {
            get {
                return ResourceManager.GetString("Notification_Field_Positive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Notification_Field_Searching.
        /// </summary>
        public static string Notification_Field_Searching {
            get {
                return ResourceManager.GetString("Notification_Field_Searching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Notification_Field_TooLong.
        /// </summary>
        public static string Notification_Field_TooLong {
            get {
                return ResourceManager.GetString("Notification_Field_TooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Notification_Field_TooShort.
        /// </summary>
        public static string Notification_Field_TooShort {
            get {
                return ResourceManager.GetString("Notification_Field_TooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Notification_Field_Update.
        /// </summary>
        public static string Notification_Field_Update {
            get {
                return ResourceManager.GetString("Notification_Field_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Notification_Field_Updated.
        /// </summary>
        public static string Notification_Field_Updated {
            get {
                return ResourceManager.GetString("Notification_Field_Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Notification_Field_Updating.
        /// </summary>
        public static string Notification_Field_Updating {
            get {
                return ResourceManager.GetString("Notification_Field_Updating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Notification_Field_WrongFormat.
        /// </summary>
        public static string Notification_Field_WrongFormat {
            get {
                return ResourceManager.GetString("Notification_Field_WrongFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Notification_Field_X_Invalid.
        /// </summary>
        public static string Notification_Field_X_Invalid {
            get {
                return ResourceManager.GetString("Notification_Field_X_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Notification_Field_X_CharShort.
        /// </summary>
        public static string Notification_Field_X_Length {
            get {
                return ResourceManager.GetString("Notification_Field_X_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Notification_Field_CharOnly.
        /// </summary>
        public static string Notification_Field_X_MaxLength {
            get {
                return ResourceManager.GetString("Notification_Field_X_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Notification_Field_X_CharLong.
        /// </summary>
        public static string Notification_Field_X_MinLength {
            get {
                return ResourceManager.GetString("Notification_Field_X_MinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Notification_Field_X_Valid.
        /// </summary>
        public static string Notification_Field_X_Valid {
            get {
                return ResourceManager.GetString("Notification_Field_X_Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Notification_Info.
        /// </summary>
        public static string Notification_Info {
            get {
                return ResourceManager.GetString("Notification_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Notification_Internal.
        /// </summary>
        public static string Notification_Internal {
            get {
                return ResourceManager.GetString("Notification_Internal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Notification_List_Updated.
        /// </summary>
        public static string Notification_List_Updated {
            get {
                return ResourceManager.GetString("Notification_List_Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Notification_List_Updating.
        /// </summary>
        public static string Notification_List_Updating {
            get {
                return ResourceManager.GetString("Notification_List_Updating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Notification_Lists_Updates.
        /// </summary>
        public static string Notification_Lists_Updates {
            get {
                return ResourceManager.GetString("Notification_Lists_Updates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Notification_Lists_Updating.
        /// </summary>
        public static string Notification_Lists_Updating {
            get {
                return ResourceManager.GetString("Notification_Lists_Updating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Notification_Navigator_View_ResolveFirst.
        /// </summary>
        public static string Notification_Navigator_View_ResolveFirst {
            get {
                return ResourceManager.GetString("Notification_Navigator_View_ResolveFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Notification_Navigator_ViewModel_ResolveFirst.
        /// </summary>
        public static string Notification_Navigator_ViewModel_ResolveFirst {
            get {
                return ResourceManager.GetString("Notification_Navigator_ViewModel_ResolveFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Notification_RequisitionFailed.
        /// </summary>
        public static string Notification_RequisitionFailed {
            get {
                return ResourceManager.GetString("Notification_RequisitionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Notification_RequisitionSucessful.
        /// </summary>
        public static string Notification_RequisitionSucessful {
            get {
                return ResourceManager.GetString("Notification_RequisitionSucessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @UI_Header_Alter.
        /// </summary>
        public static string UI_Header_Alter {
            get {
                return ResourceManager.GetString("UI_Header_Alter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @UI_Header_Alter_Address.
        /// </summary>
        public static string UI_Header_Alter_Address {
            get {
                return ResourceManager.GetString("UI_Header_Alter_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @UI_Header_Alter_BaseEntity.
        /// </summary>
        public static string UI_Header_Alter_BaseEntity {
            get {
                return ResourceManager.GetString("UI_Header_Alter_BaseEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @UI_Header_Alter_Category.
        /// </summary>
        public static string UI_Header_Alter_Category {
            get {
                return ResourceManager.GetString("UI_Header_Alter_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @UI_Header_Alter_ContactInfo.
        /// </summary>
        public static string UI_Header_Alter_ContactInfo {
            get {
                return ResourceManager.GetString("UI_Header_Alter_ContactInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @UI_Header_Alter_Customer.
        /// </summary>
        public static string UI_Header_Alter_Customer {
            get {
                return ResourceManager.GetString("UI_Header_Alter_Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @UI_Header_Alter_Email.
        /// </summary>
        public static string UI_Header_Alter_Email {
            get {
                return ResourceManager.GetString("UI_Header_Alter_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @UI_Header_Alter_Employee.
        /// </summary>
        public static string UI_Header_Alter_Employee {
            get {
                return ResourceManager.GetString("UI_Header_Alter_Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @UI_Header_Alter_LegalPerson.
        /// </summary>
        public static string UI_Header_Alter_LegalPerson {
            get {
                return ResourceManager.GetString("UI_Header_Alter_LegalPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @UI_Header_Alter_NaturalPerson.
        /// </summary>
        public static string UI_Header_Alter_NaturalPerson {
            get {
                return ResourceManager.GetString("UI_Header_Alter_NaturalPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @UI_Header_Alter_PayCheck.
        /// </summary>
        public static string UI_Header_Alter_PayCheck {
            get {
                return ResourceManager.GetString("UI_Header_Alter_PayCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @UI_Header_Alter_Person.
        /// </summary>
        public static string UI_Header_Alter_Person {
            get {
                return ResourceManager.GetString("UI_Header_Alter_Person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @UI_Header_Alter_PhoneNumber.
        /// </summary>
        public static string UI_Header_Alter_PhoneNumber {
            get {
                return ResourceManager.GetString("UI_Header_Alter_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @UI_Header_Alter_Product.
        /// </summary>
        public static string UI_Header_Alter_Product {
            get {
                return ResourceManager.GetString("UI_Header_Alter_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @UI_Header_Alter_Sale.
        /// </summary>
        public static string UI_Header_Alter_Sale {
            get {
                return ResourceManager.GetString("UI_Header_Alter_Sale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @UI_Header_Alter_Service.
        /// </summary>
        public static string UI_Header_Alter_Service {
            get {
                return ResourceManager.GetString("UI_Header_Alter_Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @UI_Header_List.
        /// </summary>
        public static string UI_Header_List {
            get {
                return ResourceManager.GetString("UI_Header_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @UI_Header_List_Address.
        /// </summary>
        public static string UI_Header_List_Address {
            get {
                return ResourceManager.GetString("UI_Header_List_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @UI_Header_List_BaseEntity.
        /// </summary>
        public static string UI_Header_List_BaseEntity {
            get {
                return ResourceManager.GetString("UI_Header_List_BaseEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @UI_Header_List_Category.
        /// </summary>
        public static string UI_Header_List_Category {
            get {
                return ResourceManager.GetString("UI_Header_List_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @UI_Header_List_Client.
        /// </summary>
        public static string UI_Header_List_Client {
            get {
                return ResourceManager.GetString("UI_Header_List_Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @UI_Header_List_ContactInfo.
        /// </summary>
        public static string UI_Header_List_ContactInfo {
            get {
                return ResourceManager.GetString("UI_Header_List_ContactInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @UI_Header_List_Customer.
        /// </summary>
        public static string UI_Header_List_Customer {
            get {
                return ResourceManager.GetString("UI_Header_List_Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @UI_Header_List_Email.
        /// </summary>
        public static string UI_Header_List_Email {
            get {
                return ResourceManager.GetString("UI_Header_List_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @UI_Header_List_Employee.
        /// </summary>
        public static string UI_Header_List_Employee {
            get {
                return ResourceManager.GetString("UI_Header_List_Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @UI_Header_List_Op.
        /// </summary>
        public static string UI_Header_List_Op {
            get {
                return ResourceManager.GetString("UI_Header_List_Op", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @UI_Header_List_PhoneNumber.
        /// </summary>
        public static string UI_Header_List_PhoneNumber {
            get {
                return ResourceManager.GetString("UI_Header_List_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @UI_Header_List_Product.
        /// </summary>
        public static string UI_Header_List_Product {
            get {
                return ResourceManager.GetString("UI_Header_List_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @UI_Header_List_Sale.
        /// </summary>
        public static string UI_Header_List_Sale {
            get {
                return ResourceManager.GetString("UI_Header_List_Sale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @UI_Header_ListService.
        /// </summary>
        public static string UI_Header_List_Service {
            get {
                return ResourceManager.GetString("UI_Header_List_Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @UI_Header_Main_Busy.
        /// </summary>
        public static string UI_Header_Main_Busy {
            get {
                return ResourceManager.GetString("UI_Header_Main_Busy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @UI_Header_Main_Column.
        /// </summary>
        public static string UI_Header_Main_Column {
            get {
                return ResourceManager.GetString("UI_Header_Main_Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @UI_Header_Main_Header.
        /// </summary>
        public static string UI_Header_Main_Header {
            get {
                return ResourceManager.GetString("UI_Header_Main_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @UI_Header_Main_Message.
        /// </summary>
        public static string UI_Header_Main_Message {
            get {
                return ResourceManager.GetString("UI_Header_Main_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @UI_Header_Sell.
        /// </summary>
        public static string UI_Header_Sell {
            get {
                return ResourceManager.GetString("UI_Header_Sell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @UI_Header_Sell_Product.
        /// </summary>
        public static string UI_Header_Sell_Product {
            get {
                return ResourceManager.GetString("UI_Header_Sell_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @UI_Header_Sell_Service.
        /// </summary>
        public static string UI_Header_Sell_Service {
            get {
                return ResourceManager.GetString("UI_Header_Sell_Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @UI_Menu_File.
        /// </summary>
        public static string UI_Menu_File {
            get {
                return ResourceManager.GetString("UI_Menu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @UI_Menu_Quit.
        /// </summary>
        public static string UI_Menu_File_Quit {
            get {
                return ResourceManager.GetString("UI_Menu_File_Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @UI_Menu_Save.
        /// </summary>
        public static string UI_Menu_File_Save {
            get {
                return ResourceManager.GetString("UI_Menu_File_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @UI_Menu_List.
        /// </summary>
        public static string UI_Menu_List {
            get {
                return ResourceManager.GetString("UI_Menu_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @UI_Menu_List_Client.
        /// </summary>
        public static string UI_Menu_List_Client {
            get {
                return ResourceManager.GetString("UI_Menu_List_Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @UI_Menu_List_Company.
        /// </summary>
        public static string UI_Menu_List_Company {
            get {
                return ResourceManager.GetString("UI_Menu_List_Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @UI_Menu_List_Employee.
        /// </summary>
        public static string UI_Menu_List_Employee {
            get {
                return ResourceManager.GetString("UI_Menu_List_Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @UI_Menu_List_Product.
        /// </summary>
        public static string UI_Menu_List_Product {
            get {
                return ResourceManager.GetString("UI_Menu_List_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @UI_Menu_List_Supplier.
        /// </summary>
        public static string UI_Menu_List_Supplier {
            get {
                return ResourceManager.GetString("UI_Menu_List_Supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @UI_Menu_Register.
        /// </summary>
        public static string UI_Menu_Register {
            get {
                return ResourceManager.GetString("UI_Menu_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @UI_Menu_Register_Client.
        /// </summary>
        public static string UI_Menu_Register_Client {
            get {
                return ResourceManager.GetString("UI_Menu_Register_Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @UI_Menu_Register_Company.
        /// </summary>
        public static string UI_Menu_Register_Company {
            get {
                return ResourceManager.GetString("UI_Menu_Register_Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @UI_Menu_Register_Employee.
        /// </summary>
        public static string UI_Menu_Register_Employee {
            get {
                return ResourceManager.GetString("UI_Menu_Register_Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @UI_Menu_Register_Product.
        /// </summary>
        public static string UI_Menu_Register_Product {
            get {
                return ResourceManager.GetString("UI_Menu_Register_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @UI_Menu_Register_Supplier.
        /// </summary>
        public static string UI_Menu_Register_Supplier {
            get {
                return ResourceManager.GetString("UI_Menu_Register_Supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @UI_Menu_Report.
        /// </summary>
        public static string UI_Menu_Report {
            get {
                return ResourceManager.GetString("UI_Menu_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @UI_Menu_Sales.
        /// </summary>
        public static string UI_Menu_Sales {
            get {
                return ResourceManager.GetString("UI_Menu_Sales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @UI_Menu_Sales_Alter.
        /// </summary>
        public static string UI_Menu_Sales_Alter {
            get {
                return ResourceManager.GetString("UI_Menu_Sales_Alter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @UI_Menu_Sales_History.
        /// </summary>
        public static string UI_Menu_Sales_History {
            get {
                return ResourceManager.GetString("UI_Menu_Sales_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @UI_Menu_Sales_New.
        /// </summary>
        public static string UI_Menu_Sales_New {
            get {
                return ResourceManager.GetString("UI_Menu_Sales_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @UI_Menu_Util.
        /// </summary>
        public static string UI_Menu_Util {
            get {
                return ResourceManager.GetString("UI_Menu_Util", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @UI_Menu_Util_Address.
        /// </summary>
        public static string UI_Menu_Util_Address {
            get {
                return ResourceManager.GetString("UI_Menu_Util_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @UI_Menu_Util_Comission.
        /// </summary>
        public static string UI_Menu_Util_Comission {
            get {
                return ResourceManager.GetString("UI_Menu_Util_Comission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @UI_Menu_Util_ContactInfo.
        /// </summary>
        public static string UI_Menu_Util_ContactInfo {
            get {
                return ResourceManager.GetString("UI_Menu_Util_ContactInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @UI_Menu_Util_Paycheck.
        /// </summary>
        public static string UI_Menu_Util_Paycheck {
            get {
                return ResourceManager.GetString("UI_Menu_Util_Paycheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App_Title.
        /// </summary>
        public static string UI_Title_Shell {
            get {
                return ResourceManager.GetString("UI_Title_Shell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @UI_ToolTip_Add.
        /// </summary>
        public static string UI_ToolTip_Add {
            get {
                return ResourceManager.GetString("UI_ToolTip_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @UI_ToolTip_AlterCustomer.
        /// </summary>
        public static string UI_ToolTip_AlterCustomer {
            get {
                return ResourceManager.GetString("UI_ToolTip_AlterCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @UI_ToolTip_Cancel.
        /// </summary>
        public static string UI_ToolTip_Cancel {
            get {
                return ResourceManager.GetString("UI_ToolTip_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @UI_ToolTip_Clear.
        /// </summary>
        public static string UI_ToolTip_Clear {
            get {
                return ResourceManager.GetString("UI_ToolTip_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @UI_ToolTip_Close.
        /// </summary>
        public static string UI_ToolTip_Close {
            get {
                return ResourceManager.GetString("UI_ToolTip_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @UI_ToolTip_Code.
        /// </summary>
        public static string UI_ToolTip_Code {
            get {
                return ResourceManager.GetString("UI_ToolTip_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @UI_ToolTip_Confirm.
        /// </summary>
        public static string UI_ToolTip_Confirm {
            get {
                return ResourceManager.GetString("UI_ToolTip_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @UI_ToolTip_Delete.
        /// </summary>
        public static string UI_ToolTip_Delete {
            get {
                return ResourceManager.GetString("UI_ToolTip_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @UI_ToolTip_Edit.
        /// </summary>
        public static string UI_ToolTip_Edit {
            get {
                return ResourceManager.GetString("UI_ToolTip_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @UI_ToolTip_Filter.
        /// </summary>
        public static string UI_ToolTip_Filter {
            get {
                return ResourceManager.GetString("UI_ToolTip_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @UI_ToolTip_List.
        /// </summary>
        public static string UI_ToolTip_List {
            get {
                return ResourceManager.GetString("UI_ToolTip_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @UI_ToolTip_Login.
        /// </summary>
        public static string UI_ToolTip_Login {
            get {
                return ResourceManager.GetString("UI_ToolTip_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @UI_ToolTip_Logout.
        /// </summary>
        public static string UI_ToolTip_Logout {
            get {
                return ResourceManager.GetString("UI_ToolTip_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @UI_ToolTip_Messages.
        /// </summary>
        public static string UI_ToolTip_Messages {
            get {
                return ResourceManager.GetString("UI_ToolTip_Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @UI_ToolTip_Notifications.
        /// </summary>
        public static string UI_ToolTip_Notifications {
            get {
                return ResourceManager.GetString("UI_ToolTip_Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @UI_ToolTip_Operations.
        /// </summary>
        public static string UI_ToolTip_Operations {
            get {
                return ResourceManager.GetString("UI_ToolTip_Operations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @UI_ToolTip_QuickSearch.
        /// </summary>
        public static string UI_ToolTip_QuickSearch {
            get {
                return ResourceManager.GetString("UI_ToolTip_QuickSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @UI_ToolTip_Sales.
        /// </summary>
        public static string UI_ToolTip_Sales {
            get {
                return ResourceManager.GetString("UI_ToolTip_Sales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @UI_ToolTip_Search.
        /// </summary>
        public static string UI_ToolTip_Search {
            get {
                return ResourceManager.GetString("UI_ToolTip_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @UI_ToolTip_Update.
        /// </summary>
        public static string UI_ToolTip_Update {
            get {
                return ResourceManager.GetString("UI_ToolTip_Update", resourceCulture);
            }
        }
    }
}
