//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOB.UI.Core.View.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LOB.UI.Core.View.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Button_Close.
        /// </summary>
        public static string Button_Close {
            get {
                return ResourceManager.GetString("Button_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Address.
        /// </summary>
        public static string Common_Address {
            get {
                return ResourceManager.GetString("Common_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_AvailableInStore.
        /// </summary>
        public static string Common_AvailableInStore {
            get {
                return ResourceManager.GetString("Common_AvailableInStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_BirthDate.
        /// </summary>
        public static string Common_BirthDate {
            get {
                return ResourceManager.GetString("Common_BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Bonus.
        /// </summary>
        public static string Common_Bonus {
            get {
                return ResourceManager.GetString("Common_Bonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_BoughtHistory.
        /// </summary>
        public static string Common_BoughtHistory {
            get {
                return ResourceManager.GetString("Common_BoughtHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Category.
        /// </summary>
        public static string Common_Category {
            get {
                return ResourceManager.GetString("Common_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_City.
        /// </summary>
        public static string Common_City {
            get {
                return ResourceManager.GetString("Common_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_CnaeFiscal.
        /// </summary>
        public static string Common_CnaeFiscal {
            get {
                return ResourceManager.GetString("Common_CnaeFiscal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Cnpj.
        /// </summary>
        public static string Common_Cnpj {
            get {
                return ResourceManager.GetString("Common_Cnpj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Code.
        /// </summary>
        public static string Common_Code {
            get {
                return ResourceManager.GetString("Common_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Complement.
        /// </summary>
        public static string Common_Complement {
            get {
                return ResourceManager.GetString("Common_Complement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Contact.
        /// </summary>
        public static string Common_Contact {
            get {
                return ResourceManager.GetString("Common_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_ContactInfo.
        /// </summary>
        public static string Common_ContactInfo {
            get {
                return ResourceManager.GetString("Common_ContactInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_CorporateName.
        /// </summary>
        public static string Common_CorporateName {
            get {
                return ResourceManager.GetString("Common_CorporateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Country.
        /// </summary>
        public static string Common_Country {
            get {
                return ResourceManager.GetString("Common_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Cpf.
        /// </summary>
        public static string Common_Cpf {
            get {
                return ResourceManager.GetString("Common_Cpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_CurrentSalary.
        /// </summary>
        public static string Common_CurrentSalary {
            get {
                return ResourceManager.GetString("Common_CurrentSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Customer.
        /// </summary>
        public static string Common_Customer {
            get {
                return ResourceManager.GetString("Common_Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_CustomerOf.
        /// </summary>
        public static string Common_CustomerOf {
            get {
                return ResourceManager.GetString("Common_CustomerOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Date.
        /// </summary>
        public static string Common_Date {
            get {
                return ResourceManager.GetString("Common_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Default.
        /// </summary>
        public static string Common_Default {
            get {
                return ResourceManager.GetString("Common_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Description.
        /// </summary>
        public static string Common_Description {
            get {
                return ResourceManager.GetString("Common_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_District.
        /// </summary>
        public static string Common_District {
            get {
                return ResourceManager.GetString("Common_District", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Email.
        /// </summary>
        public static string Common_Email {
            get {
                return ResourceManager.GetString("Common_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Emails.
        /// </summary>
        public static string Common_Emails {
            get {
                return ResourceManager.GetString("Common_Emails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_FirstName.
        /// </summary>
        public static string Common_FirstName {
            get {
                return ResourceManager.GetString("Common_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_HireDate.
        /// </summary>
        public static string Common_HireDate {
            get {
                return ResourceManager.GetString("Common_HireDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_InscEstadual.
        /// </summary>
        public static string Common_InscEstadual {
            get {
                return ResourceManager.GetString("Common_InscEstadual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_InscMunicipal.
        /// </summary>
        public static string Common_InscMunicipal {
            get {
                return ResourceManager.GetString("Common_InscMunicipal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_LastName.
        /// </summary>
        public static string Common_LastName {
            get {
                return ResourceManager.GetString("Common_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Name.
        /// </summary>
        public static string Common_Name {
            get {
                return ResourceManager.GetString("Common_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_NickName.
        /// </summary>
        public static string Common_NickName {
            get {
                return ResourceManager.GetString("Common_NickName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Notes.
        /// </summary>
        public static string Common_Notes {
            get {
                return ResourceManager.GetString("Common_Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Number.
        /// </summary>
        public static string Common_Number {
            get {
                return ResourceManager.GetString("Common_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_PayCheck.
        /// </summary>
        public static string Common_PayCheck {
            get {
                return ResourceManager.GetString("Common_PayCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_PersonDetails.
        /// </summary>
        public static string Common_PersonDetails {
            get {
                return ResourceManager.GetString("Common_PersonDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_PersonType.
        /// </summary>
        public static string Common_PersonType {
            get {
                return ResourceManager.GetString("Common_PersonType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_PhoneNumber.
        /// </summary>
        public static string Common_PhoneNumber {
            get {
                return ResourceManager.GetString("Common_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_PhoneNumbers.
        /// </summary>
        public static string Common_PhoneNumbers {
            get {
                return ResourceManager.GetString("Common_PhoneNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Product.
        /// </summary>
        public static string Common_Product {
            get {
                return ResourceManager.GetString("Common_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Products.
        /// </summary>
        public static string Common_Products {
            get {
                return ResourceManager.GetString("Common_Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Ps.
        /// </summary>
        public static string Common_Ps {
            get {
                return ResourceManager.GetString("Common_Ps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_QuantityPerUnity.
        /// </summary>
        public static string Common_QuantityPerUnity {
            get {
                return ResourceManager.GetString("Common_QuantityPerUnity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Rg.
        /// </summary>
        public static string Common_Rg {
            get {
                return ResourceManager.GetString("Common_Rg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Search.
        /// </summary>
        public static string Common_Search {
            get {
                return ResourceManager.GetString("Common_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_State.
        /// </summary>
        public static string Common_State {
            get {
                return ResourceManager.GetString("Common_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Status.
        /// </summary>
        public static string Common_Status {
            get {
                return ResourceManager.GetString("Common_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Stores.
        /// </summary>
        public static string Common_Stores {
            get {
                return ResourceManager.GetString("Common_Stores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Street.
        /// </summary>
        public static string Common_Street {
            get {
                return ResourceManager.GetString("Common_Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_StreetNumber.
        /// </summary>
        public static string Common_StreetNumber {
            get {
                return ResourceManager.GetString("Common_StreetNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Suppliers.
        /// </summary>
        public static string Common_Suppliers {
            get {
                return ResourceManager.GetString("Common_Suppliers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Title.
        /// </summary>
        public static string Common_Title {
            get {
                return ResourceManager.GetString("Common_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_TotalValue.
        /// </summary>
        public static string Common_TotalValue {
            get {
                return ResourceManager.GetString("Common_TotalValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_TradingName.
        /// </summary>
        public static string Common_TradingName {
            get {
                return ResourceManager.GetString("Common_TradingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_UnitSalePrice.
        /// </summary>
        public static string Common_UnitSalePrice {
            get {
                return ResourceManager.GetString("Common_UnitSalePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_UnitsInStock.
        /// </summary>
        public static string Common_UnitsInStock {
            get {
                return ResourceManager.GetString("Common_UnitsInStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_Website.
        /// </summary>
        public static string Common_Website {
            get {
                return ResourceManager.GetString("Common_Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_WorkInStore.
        /// </summary>
        public static string Common_WorkInStore {
            get {
                return ResourceManager.GetString("Common_WorkInStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Common_ZipCode.
        /// </summary>
        public static string Common_ZipCode {
            get {
                return ResourceManager.GetString("Common_ZipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Menu_File.
        /// </summary>
        public static string Menu_File {
            get {
                return ResourceManager.GetString("Menu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Menu_Quit.
        /// </summary>
        public static string Menu_File_Quit {
            get {
                return ResourceManager.GetString("Menu_File_Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Menu_Save.
        /// </summary>
        public static string Menu_File_Save {
            get {
                return ResourceManager.GetString("Menu_File_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Menu_List.
        /// </summary>
        public static string Menu_List {
            get {
                return ResourceManager.GetString("Menu_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Menu_List_Client.
        /// </summary>
        public static string Menu_List_Client {
            get {
                return ResourceManager.GetString("Menu_List_Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Menu_List_Company.
        /// </summary>
        public static string Menu_List_Company {
            get {
                return ResourceManager.GetString("Menu_List_Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Menu_List_Employee.
        /// </summary>
        public static string Menu_List_Employee {
            get {
                return ResourceManager.GetString("Menu_List_Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Menu_List_Product.
        /// </summary>
        public static string Menu_List_Product {
            get {
                return ResourceManager.GetString("Menu_List_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Menu_List_Supplier.
        /// </summary>
        public static string Menu_List_Supplier {
            get {
                return ResourceManager.GetString("Menu_List_Supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Menu_Register.
        /// </summary>
        public static string Menu_Register {
            get {
                return ResourceManager.GetString("Menu_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Menu_Register_Client.
        /// </summary>
        public static string Menu_Register_Client {
            get {
                return ResourceManager.GetString("Menu_Register_Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Menu_Register_Company.
        /// </summary>
        public static string Menu_Register_Company {
            get {
                return ResourceManager.GetString("Menu_Register_Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Menu_Register_Employee.
        /// </summary>
        public static string Menu_Register_Employee {
            get {
                return ResourceManager.GetString("Menu_Register_Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Menu_Register_Product.
        /// </summary>
        public static string Menu_Register_Product {
            get {
                return ResourceManager.GetString("Menu_Register_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Menu_Register_Supplier.
        /// </summary>
        public static string Menu_Register_Supplier {
            get {
                return ResourceManager.GetString("Menu_Register_Supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Menu_Report.
        /// </summary>
        public static string Menu_Report {
            get {
                return ResourceManager.GetString("Menu_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Menu_Sales.
        /// </summary>
        public static string Menu_Sales {
            get {
                return ResourceManager.GetString("Menu_Sales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Menu_Sales_Alter.
        /// </summary>
        public static string Menu_Sales_Alter {
            get {
                return ResourceManager.GetString("Menu_Sales_Alter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Menu_Sales_History.
        /// </summary>
        public static string Menu_Sales_History {
            get {
                return ResourceManager.GetString("Menu_Sales_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Menu_Sales_New.
        /// </summary>
        public static string Menu_Sales_New {
            get {
                return ResourceManager.GetString("Menu_Sales_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Menu_Util.
        /// </summary>
        public static string Menu_Util {
            get {
                return ResourceManager.GetString("Menu_Util", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Menu_Util_Address.
        /// </summary>
        public static string Menu_Util_Address {
            get {
                return ResourceManager.GetString("Menu_Util_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Menu_Util_Comission.
        /// </summary>
        public static string Menu_Util_Comission {
            get {
                return ResourceManager.GetString("Menu_Util_Comission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Menu_Util_ContactInfo.
        /// </summary>
        public static string Menu_Util_ContactInfo {
            get {
                return ResourceManager.GetString("Menu_Util_ContactInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Menu_Util_Paycheck.
        /// </summary>
        public static string Menu_Util_Paycheck {
            get {
                return ResourceManager.GetString("Menu_Util_Paycheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Tab_Hide.
        /// </summary>
        public static string Tab_Hide {
            get {
                return ResourceManager.GetString("Tab_Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @ToolTip_AlterCustomer.
        /// </summary>
        public static string ToolTip_AlterCustomer {
            get {
                return ResourceManager.GetString("ToolTip_AlterCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @ToolTip_Clear.
        /// </summary>
        public static string ToolTip_Clear {
            get {
                return ResourceManager.GetString("ToolTip_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @ToolTip_Close.
        /// </summary>
        public static string ToolTip_Close {
            get {
                return ResourceManager.GetString("ToolTip_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @ToolTip_Code.
        /// </summary>
        public static string ToolTip_Code {
            get {
                return ResourceManager.GetString("ToolTip_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @ToolTip_Operations.
        /// </summary>
        public static string ToolTip_Operations {
            get {
                return ResourceManager.GetString("ToolTip_Operations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @ToolTip_QuickSearch.
        /// </summary>
        public static string ToolTip_QuickSearch {
            get {
                return ResourceManager.GetString("ToolTip_QuickSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @ToolTip_Sales.
        /// </summary>
        public static string ToolTip_Sales {
            get {
                return ResourceManager.GetString("ToolTip_Sales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Window_Title.
        /// </summary>
        public static string Window_Title {
            get {
                return ResourceManager.GetString("Window_Title", resourceCulture);
            }
        }
    }
}
